services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    tty: true
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}